language: python

addons:
    apt:
        packages:
            - libopenmpi-dev
            - openmpi-bin

python:
    - 2.6
    - 2.7
    - 3.4
    - 3.3

before_install:

install:
    - cp Options.mk.example Options.mk
    - make bcast

script:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - conda install --yes numpy  nose
    - conda install --yes mpich2 mpi4py
    - source deactivate
    - bash tar-anaconda.sh anaconda.tar.gz $HOME/miniconda/envs/test
    - bash runtest.sh
